name:                workshop6

dependencies:
- base
- doctest
- QuickCheck
- Glob

executables:
  workshop6:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - workshop6

library:
  source-dirs: src/week6

tests:
  workshop6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - workshop6


