name:                workshop7

dependencies:
- base >= 4.7 && < 5
- doctest >= 0.11
- QuickCheck >= 2.8
- Glob >= 0.7.14

executables:
  workshop7:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - workshop7

library:
  source-dirs: src/

tests:
  workshop7-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - workshop7


